apiVersion: v1
kind: ConfigMap
metadata:
  namespace: warehouse
  name: serviceconfig
  labels:
    app: simple-shop
    team: beta
data:
  svcconfig: |-
    {
      "logging": {
        "logLevel": {
          "default": "Information"
        },
        "logger": "fluentd"
      },
      
      "bus": {
        "receiveEndpoint": "warehouse",
        "host": "queue.data",
        "username": "guest",
        "password": "guest",
        "tracing": "OpenTracing"
      },
      
      "tracing": {
          "tracer": "jaeger",
          "jaegerAgent": "jaeger-agent.skywalking",
          "jaegerUrl": "jaeger-collector.istio-system",
          "dataDogUrl": "datadog.datadog"
      },

      "database": {
        "connectionString": "host=document.data;database=Warehouse;password=ABC123!!;username=application"
      }
    }

