apiVersion: v1
kind: Service
metadata:
  namespace: warehouse
  labels:
    app: simple-shop
    component: warehouse
  name: warehouse
spec:
  ports:
  - name: http
    protocol: TCP
    port: 7004
    targetPort: 7004
  selector:
    app: simple-shop
    component: warehouse