apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: warehouse
  name: warehouse
spec:
  template:
    metadata:
      labels:
        app: simple-shop
        component: warehouse
        team: beta
    spec:
      containers:
        - name: warehouse
          image: dbonessimplestore/warehouse:latest
          imagePullPolicy: Always
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /hc
              port: 7004
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 2
            timeoutSeconds: 2
          # resources:
          #   limits:
          #     memory: 512Mi
          #   requests:
          #     memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: serviceconfig
            items:
              - key: svcconfig
                path: stagesettings.json